In [2]:
import pandas as pd

In [3]:
df=pd.read_csv('data/gems_stone.csv')

In [4]:
df.head()

   id  carat        cut color clarity  depth  table     x     y     z  price
0   0   1.52    Premium     F     VS2   62.2   58.0  7.27  7.33  4.55  13619
1   1   2.03  Very Good     J     SI2   62.0   58.0  8.06  8.12  5.05  13387
2   2   0.70      Ideal     G     VS1   61.2   57.0  5.69  5.73  3.50   2772
3   3   0.32      Ideal     G     VS1   61.6   56.0  4.38  4.41  2.71    666
4   4   1.70    Premium     G     VS2   62.6   59.0  7.65  7.61  4.77  14453

In [5]:
df=df.drop(['id'],axis=1)

In [6]:
df.head()

   carat        cut color clarity  depth  table     x     y     z  price
0   1.52    Premium     F     VS2   62.2   58.0  7.27  7.33  4.55  13619
1   2.03  Very Good     J     SI2   62.0   58.0  8.06  8.12  5.05  13387
2   0.70      Ideal     G     VS1   61.2   57.0  5.69  5.73  3.50   2772
3   0.32      Ideal     G     VS1   61.6   56.0  4.38  4.41  2.71    666
4   1.70    Premium     G     VS2   62.6   59.0  7.65  7.61  4.77  14453

In [7]:
#segregating dependent and independent features
X=df.drop(['price'],axis=1)
y=df[['price']]

In [8]:
categorical_features=X.columns[X.dtypes=='O'] #categorical_features=X.select_dtypes(include='object').columns
numerical_features=X.columns[X.dtypes!='O'] #numerical_features=X.select_dtypes(exclude='object').columns

In [9]:
cut_categories = ['Fair', 'Good', 'Very Good','Premium','Ideal']
color_categories = ['D', 'E', 'F', 'G', 'H', 'I', 'J']
clarity_categories = ['I1','SI2','SI1','VS2','VS1','VVS2','VVS1','IF']

#category=[]
#for i in categorical_features:
    #x=list(df[i].unique())
    #category.append(x)

In [10]:
from sklearn.impute import SimpleImputer #for handling missing values
from sklearn.preprocessing import StandardScaler #for handling feature scaling
from sklearn.preprocessing import OrdinalEncoder #ordinal encoder

from sklearn.pipeline import Pipeline #for combining multiple steps
from sklearn.compose import ColumnTransformer

In [11]:
##Numerical pipeline
num_pipeline=Pipeline(
    steps=[
    ('Imputer',SimpleImputer(strategy='median')),
    ('scalar',StandardScaler())
       ]
)
##categorical pipeline
cat_pipeline=Pipeline(
    steps=[
    ('imputer',SimpleImputer(strategy='most_frequent')),
    ('ordinalencoder',OrdinalEncoder(categories=[cut_categories,color_categories,clarity_categories])),
    ('scalar',StandardScaler())
        ]
)
##combining cat and num pipelines
preprocessor=ColumnTransformer([
    ('num_pipeline',num_pipeline,numerical_features),
    ('cat_pipeline',cat_pipeline,categorical_features)
])

In [12]:
##Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.30,random_state=42)

In [13]:
X_train=pd.DataFrame(preprocessor.fit_transform(X_train),columns=preprocessor.get_feature_names_out())
X_test=pd.DataFrame(preprocessor.transform(X_test),columns=preprocessor.get_feature_names_out())

In [14]:
X_train

,num_pipeline__carat,num_pipeline__depth,num_pipeline__table,num_pipeline__x,num_pipeline__y,num_pipeline__z,cat_pipeline__cut,cat_pipeline__color,cat_pipeline__clarity
0,-0.823144,-1.129988,-0.641897,-0.780451,-0.835103,-0.876024,0.874100,-0.936747,1.350746
1,0.945023,-1.777823,0.921902,1.073226,1.166389,0.946633,-1.137644,0.910853,0.684455
2,1.958484,0.165682,0.400636,1.703116,1.755063,1.742237,-0.131772,0.910853,0.018164
3,-0.995648,-0.574701,-0.641897,-1.122391,-1.161138,-1.165334,0.874100,-0.320880,2.017037
4,-0.995648,0.258230,0.400636,-1.176382,-1.152082,-1.136403,-1.137644,1.526720,-0.648127
...,...,...,...,...,...,...,...,...,...
135496,-0.629077,-1.500179,1.964434,-0.546492,-0.518125,-0.644575,-1.137644,-0.936747,-0.648127
135497,2.411307,0.443325,2.485700,1.919078,1.872797,1.930288,-1.137644,-0.320880,-0.648127
135498,0.923460,0.906065,0.400636,0.992240,0.921862,1.047891,-0.131772,0.294987,0.018164
135499,-1.038774,-0.667249,-0.641897,-1.212375,-1.197364,-1.252127,-1.137644,0.294987,2.017037
135500,-1.038774,-0.019414,0.921902,-1.239371,-1.215477,-1.208731,-1.137644,0.294987,-1.314417

In [15]:
X_test

,num_pipeline__carat,num_pipeline__depth,num_pipeline__table,num_pipeline__x,num_pipeline__y,num_pipeline__z,cat_pipeline__cut,cat_pipeline__color,cat_pipeline__clarity
0,-0.629077,0.258230,-0.120630,-0.600482,-0.581521,-0.572248,0.874100,-1.552614,-0.648127
1,2.605374,-2.148014,-0.120630,2.126042,2.198832,1.959219,-1.137644,0.294987,-1.314417
2,-1.125026,-1.222536,0.921902,-1.374347,-1.414721,-1.469110,-0.131772,-0.936747,2.017037
3,-1.017211,-0.574701,0.921902,-1.158385,-1.161138,-1.194265,-0.131772,1.526720,2.017037
4,0.858771,0.628421,-0.641897,0.947248,0.985258,1.004495,0.874100,0.910853,-0.648127
...,...,...,...,...,...,...,...,...,...
58067,0.255007,0.535873,0.921902,0.416340,0.369414,0.425874,-1.137644,1.526720,-1.314417
58068,-0.607514,0.535873,-0.641897,-0.528495,-0.554351,-0.499920,0.874100,-1.552614,0.018164
58069,-0.823144,-0.019414,-0.641897,-0.834441,-0.862273,-0.847093,0.874100,0.294987,2.017037
58070,0.901897,-0.667249,1.443168,1.046230,0.967145,0.932167,-0.131772,1.526720,-0.648127
58071,0.470637,0.906065,-0.641897,0.551317,0.668280,0.700719,-1.137644,-0.936747,0.018164

In [16]:
##Model Training
from sklearn.linear_model import LinearRegression,Lasso,Ridge,ElasticNet
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [17]:
import numpy as np
def evaluate_model(true,predicted):
    mse=mean_squared_error(true,predicted)
    mae=mean_absolute_error(true,predicted)
    rmse=np.sqrt(mse)
    rsq=r2_score(true,predicted)
    return mse,mae,rmse,rsq

In [18]:
models={
    'linear regression':LinearRegression(),
    'lasso':Lasso(),
    'ridge':Ridge(),
    'elastic net':ElasticNet()
}

model_list=[]
rsq_list=[]
for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(X_train,y_train)

    y_pred=model.predict(X_test)
    mse,mae,rmse,rsq=evaluate_model(y_test,y_pred)

    print(list(models.keys())[i])
    model_list.append(list(models.keys())[i])
    rsq_list.append(rsq*100)
    print('model training performance :')
    print('MSE :',mse)
    print('MAE :',mae)
    print('RMSE:',rmse)
    print('R-Sq:',rsq*100)
    print("="*30,'\n')

linear regression
model training performance :
MSE : 1029473.3531156853
MAE : 675.0758270067466
RMSE: 1014.6296630375466
R-Sq: 93.62906819996047
==============================

lasso
model training performance :
MSE : 1029533.1506505492
MAE : 676.242117366551
RMSE: 1014.659130275064
R-Sq: 93.62869814082755
==============================

ridge
model training performance :
MSE : 1029482.810126902
MAE : 675.1077629781344
RMSE: 1014.6343233534444
R-Sq: 93.62900967491628
==============================

elastic net
model training performance :
MSE : 2351174.8713978734
MAE : 1060.9432977143
RMSE: 1533.3541245902309
R-Sq: 85.44967219374031
==============================

In [19]:
model_list

['linear regression', 'lasso', 'ridge', 'elastic net']

In [20]:
rsq_list

[93.62906819996047, 93.62869814082755, 93.62900967491628, 85.44967219374031]

In [22]:
print(f'The accuracy of {model_list[rsq_list.index(max(rsq_list))]} model is more wirh R-squared value :{max(rsq_list)}')

The accuracy of linear regression model is more wirh R-squared value :93.62906819996047